name: Build Deb packages (ros-apt-source)

on:
  workflow_dispatch:

jobs:
  # build-ros2-apt-source-earthly:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       distro: [ubuntu:focal,ubuntu:jammy,ubuntu:noble,ubuntu:resolute,debian:bookworm,debian:bullseye,debian:trixie]
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Setup Earthly
  #       run: |
  #         sudo wget 'https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64' -O /usr/local/bin/earthly
  #         sudo chmod 755 /usr/local/bin/earthly
  #     - name: Build apt-source deb with Earthly
  #       run: earthly ./ros-apt-source+ros-apt-source --distro=${{ matrix.distro }}
  #     - name: Test ros 2 apt-source deb with Earthly
  #       run:  | 
  #             earthly ./ros-apt-source+test-aptsource-pkg-install --distro=${{ matrix.distro }} --repo=ros2
  #             earthly ./ros-apt-source+test-aptsource-pkg-install --distro=${{ matrix.distro }} --repo=ros2-testing

  # build-ros2-apt-source-bake:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #     - name: Build & Test deb with Docker Bake
  #       run:  docker buildx bake test-aptsource-ros2 -f ./ros-apt-source/docker-bake/docker-bake.hcl 

  # build-ros2-apt-source-bake-matrix:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       distro: [ubuntu:focal,ubuntu:jammy,ubuntu:noble,ubuntu:resolute,debian:bookworm,debian:bullseye,debian:trixie]
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #     - name: Build & Test deb with Docker Bake
  #       run:  docker buildx bake test-aptsource-ros2 -f ./ros-apt-source/docker-bake/docker-bake.hcl
  #       env:
  #         DISTRIBUTION_ROS2: ${{  matrix.distro }}

  # build-ros2-apt-source-bake-action:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #       with:
  #         driver: docker-container
  #     - name: Build and Test with Docker Bake
  #       uses: docker/bake-action@v7
  #       with:
  #         files: ./ros-apt-source/docker-bake/docker-bake.hcl
  #         targets: test-aptsource-ros2

  # build-ros2-apt-source-bake-action-matrix:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       distro: [ubuntu:focal,ubuntu:jammy,ubuntu:noble,ubuntu:resolute,debian:bookworm,debian:bullseye,debian:trixie]
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #       with:
  #         driver: docker-container
  #     - name: Build and Test with Docker Bake
  #       uses: docker/bake-action@v7
  #       with:
  #         files: ./ros-apt-source/docker-bake/docker-bake.hcl
  #         targets: test-aptsource-ros2
  #       env:
  #         DISTRIBUTION_ROS2: ${{  matrix.distro }}

  build-ros2-apt-source-dagger:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu:focal,ubuntu:jammy,ubuntu:noble,ubuntu:resolute,debian:bookworm,debian:bullseye,debian:trixie]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
            python-version: '3.12'
            cache: 'pip' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ros-apt-source/dagger/requirements.txt
      - name: Build with Dagger
        run: |
          python -m ros-apt-source.dagger.main build --distro ${{ matrix.distro }}
      - name: Test with Dagger
        run: |
          python -m ros-apt-source.dagger.main test --distro ${{ matrix.distro }} --repo ros2
          python -m ros-apt-source.dagger.main test --distro ${{ matrix.distro }} --repo ros2-testing

  # build-ros-apt-source-earthly:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       distro: [ubuntu:focal,debian:buster]
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Setup Earthly
  #       run: |
  #         sudo wget 'https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64' -O /usr/local/bin/earthly
  #         sudo chmod 755 /usr/local/bin/earthly
  #     - name: Build apt-source deb with Earthly
  #       run: earthly ./ros-apt-source+ros-apt-source --distro=${{ matrix.distro }}
  #     - name: Test ros 2 apt-source deb with Earthly
  #       run:  | 
  #             earthly ./ros-apt-source+test-aptsource-pkg-install --distro=${{ matrix.distro }} --repo=ros --version=ros
  #             earthly ./ros-apt-source+test-aptsource-pkg-install --distro=${{ matrix.distro }} --repo=ros-testing --version=ros

  # build-ros-apt-source-bake:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #     - name: Build & Test deb with Docker Bake
  #       run:  docker buildx bake test-aptsource-ros -f ./ros-apt-source/docker-bake/docker-bake.hcl 

  # build-ros-apt-source-bake-matrix:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       distro: [ubuntu:focal,debian:buster]
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #     - name: Build & Test deb with Docker Bake
  #       run:  docker buildx bake test-aptsource-ros -f ./ros-apt-source/docker-bake/docker-bake.hcl 
  #       env:
  #         DISTRIBUTION_ROS: ${{  matrix.distro }}

  # build-ros-apt-source-bake-action:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #       with:
  #         driver: docker-container
  #     - name: Build and Test with Docker Bake
  #       uses: docker/bake-action@v7
  #       with:
  #         files: ./ros-apt-source/docker-bake/docker-bake.hcl
  #         targets: test-aptsource-ros

  # build-ros-apt-source-bake-action-matrix:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       distro: [ubuntu:focal,debian:buster]
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #       with:
  #         driver: docker-container
  #     - name: Build and Test with Docker Bake
  #       uses: docker/bake-action@v7
  #       with:
  #         files: ./ros-apt-source/docker-bake/docker-bake.hcl
  #         targets: test-aptsource-ros
  #       env:
  #         DISTRIBUTION_ROS: ${{  matrix.distro }}
